# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ccbcb3e0-d217-4710-9ca0-2908553e65bf";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/d35bc571-5fcc-4eb2-91fe-0e3cdc793998";

  fileSystems."/boot" =
#    { device = "/dev/disk/by-uuid/50D9-6952";
#      fsType = "vfat";
#    };
    { device = "/dev/disk/by-uuid/F3FC-7E0E";
    };

  swapDevices = [ ];

}
